### ISSUE TITLE
Error When Running Payout Cron

### ISSUE THREAD

**Issue by daygle** [ChristianGrieger/Cryptocurrency-faucet-script#5]
When running /var/www/Faucet/cron/run.php I see the below message appear, I'm hoping your able to advise on a fix.

Are you able to provide a extract of your crontab jobs? This will assist me correctly setting up my crons.

/var/www/Faucet/cron/run.php: line 1: ?php: No such file or directory
/var/www/Faucet/cron/run.php: line 2: syntax error near unexpected token `"SIMPLE_FAUCET",true'
/var/www/Faucet/cron/run.php: line 2: `    define("SIMPLE_FAUCET",true);'

**Comment by ChristianGrieger** [comment]
1. You are running two different PHP versions/configurations for mod_php (web server) and cli_php (command line). This is possible given the odd error messages you are getting. Another fix for this would be to use curl to open the cron job (to make sure it is executed by mod_php—it's less 'clean', but it's a way to make sure if you do not have full control over the web server).

2. You have safe_mode on or an open_basedir restriction is in effect, the cronjob needs access to the parent directory in order to include the necessary files. If this is the case somehow and you do not want to disable safe_mode / the open_basedir restriction, then you can copy the cron job up a level and edit the paths inside the file. The cron job just assumes that it has access (so it doesn't test it first), which is why it results in an error if it doesn't (http://php.net/manual/en/ini.core.php#ini.open-basedir). I doubt anything like this is the case though.

3. The cron job doesn't have access to the parent directory for other (unknown) reasons.
